import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Spring, animated, easings} from 'react-spring'
import {useState} from "react";
import Link from "next/link";

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Toon<Link href="https://nextjs.org">verse</Link>
        </h1>

        <p className={styles.description}>
          Get started by joining our community! Soon, we will be available.
        </p>

        <div className={styles.grid}>
            <div className={styles.card}>
                <Spring
                    loop={{reverse: true}}
                    from={{ opacity: 1, rotateY: 0 }}
                    to={[
                        { opacity: 0.7, rotateY: 25 },
                        { opacity: 1, rotateY: 0 },
                    ]}
                    config={{duration: 2000, easing: easings.easeInOutQuart}}
                >
                    {s => (
                        <animated.div style={s}>
                            <Link href={'https://twitter.com/ToonverseClub'}>
                                <Image alt={'Twitter'} src={'/logo-twitter.svg'} width={100} height={100} />
                            </Link>
                        </animated.div>
                    )}
                </Spring>
            </div>
            <div className={styles.card}>
                <Spring
                    loop={{reverse: true}}
                    from={{ opacity: 0.7, rotateY: 25 }}
                    to={[
                        { opacity: 1, rotateY: 0 },
                        { opacity: 0.7, rotateY: 25 },
                    ]}
                    config={{duration: 2000, easing: easings.easeInOutQuart}}
                >
                    {s => (
                        <animated.div style={s}>
                            <Link href={'https://discord.gg/CAb8rcJB'}>
                                <Image alt={'Discord'} src={'/logo-discord.svg'} width={100} height={100} />
                            </Link>
                        </animated.div>
                    )}
                </Spring>
            </div>
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by{' '}<h5 className={styles.title}>Toon<span>verse</span></h5>
      </footer>
    </div>
  )
}

export default Home
